// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace toner_store.Models
{
    public partial class Toner
    {
        public Toner()
        {
            Carga = new HashSet<Carga>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Cant { get; set; }

        public virtual ICollection<Carga> Carga { get; set; }
    }
}